# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/recordable/syscall/syscall.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$src/recordable/syscall/syscall.proto\x12\x16mrr.recordable.syscall\"\xfd\x01\n\x07Syscall\x12\x16\n\x0esyscall_number\x18\x01 \x01(\r\x12\x41\n\x0breturn_only\x18\x02 \x01(\x0b\x32*.mrr.recordable.syscall.Syscall.ReturnOnlyH\x00\x12\x34\n\x04read\x18\x03 \x01(\x0b\x32$.mrr.recordable.syscall.Syscall.ReadH\x00\x1a&\n\nReturnOnly\x12\x0b\n\x03rv0\x18\x01 \x01(\x04\x12\x0b\n\x03rv1\x18\x02 \x01(\x04\x1a\x31\n\x04Read\x12\x0f\n\x05\x65rror\x18\x01 \x01(\x04H\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\x08\n\x06resultB\x06\n\x04\x64\x61tab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.recordable.syscall.syscall_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYSCALL._serialized_start=65
  _SYSCALL._serialized_end=318
  _SYSCALL_RETURNONLY._serialized_start=221
  _SYSCALL_RETURNONLY._serialized_end=259
  _SYSCALL_READ._serialized_start=261
  _SYSCALL_READ._serialized_end=310
# @@protoc_insertion_point(module_scope)
