# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/recordable/scheduling/scheduling.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*src/recordable/scheduling/scheduling.proto\x12\x19mrr.recordable.scheduling\"\xe6\x01\n\nScheduling\x12\x0b\n\x03tid\x18\x01 \x01(\r\x12@\n\x05start\x18\x02 \x01(\x0b\x32/.mrr.recordable.scheduling.Scheduling.NewThreadH\x00\x12\x45\n\x06switch\x18\x03 \x01(\x0b\x32\x33.mrr.recordable.scheduling.Scheduling.SwitchCurrentH\x00\x1a\x17\n\tNewThread\x12\n\n\x02pc\x18\x01 \x01(\x04\x1a \n\rSwitchCurrent\x12\x0f\n\x07new_tid\x18\x01 \x01(\rB\x07\n\x05\x65ventb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.recordable.scheduling.scheduling_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCHEDULING._serialized_start=74
  _SCHEDULING._serialized_end=304
  _SCHEDULING_NEWTHREAD._serialized_start=238
  _SCHEDULING_NEWTHREAD._serialized_end=261
  _SCHEDULING_SWITCHCURRENT._serialized_start=263
  _SCHEDULING_SWITCHCURRENT._serialized_end=295
# @@protoc_insertion_point(module_scope)
