# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/recordable/recordable.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.recordable.mach_trap import mach_trap_pb2 as src_dot_recordable_dot_mach__trap_dot_mach__trap__pb2
from src.recordable.scheduling import scheduling_pb2 as src_dot_recordable_dot_scheduling_dot_scheduling__pb2
from src.recordable.syscall import syscall_pb2 as src_dot_recordable_dot_syscall_dot_syscall__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fsrc/recordable/recordable.proto\x12\x0emrr.recordable\x1a(src/recordable/mach_trap/mach_trap.proto\x1a*src/recordable/scheduling/scheduling.proto\x1a$src/recordable/syscall/syscall.proto\"\x9f\x01\n\x05Trace\x12,\n\x06target\x18\x01 \x01(\x0b\x32\x1c.mrr.recordable.Trace.Target\x12(\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x18.mrr.recordable.LogEvent\x1a>\n\x06Target\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\targuments\x18\x02 \x03(\t\x12\x13\n\x0b\x65nvironment\x18\x03 \x03(\t\"\xe1\x01\n\x08LogEvent\x12\n\n\x02pc\x18\x01 \x01(\x04\x12\x16\n\x0eregister_state\x18\x02 \x03(\x04\x12\x32\n\x07syscall\x18\n \x01(\x0b\x32\x1f.mrr.recordable.syscall.SyscallH\x00\x12\x37\n\tmach_trap\x18\x0b \x01(\x0b\x32\".mrr.recordable.mach_trap.MachTrapH\x00\x12;\n\nscheduling\x18\x0c \x01(\x0b\x32%.mrr.recordable.scheduling.SchedulingH\x00\x42\x07\n\x05\x65ventb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.recordable.recordable_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRACE._serialized_start=176
  _TRACE._serialized_end=335
  _TRACE_TARGET._serialized_start=273
  _TRACE_TARGET._serialized_end=335
  _LOGEVENT._serialized_start=338
  _LOGEVENT._serialized_end=563
# @@protoc_insertion_point(module_scope)
