# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/recordable/mach_trap/mach_trap.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(src/recordable/mach_trap/mach_trap.proto\x12\x18mrr.recordable.mach_trap\"\x99\x01\n\x08MachTrap\x12\x13\n\x0btrap_number\x18\x01 \x01(\r\x12\x15\n\x0breturn_only\x18\x02 \x01(\x04H\x00\x12?\n\x08timebase\x18\x03 \x01(\x0b\x32+.mrr.recordable.mach_trap.MachTrap.TimebaseH\x00\x1a\x18\n\x08Timebase\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x42\x06\n\x04\x64\x61tab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.recordable.mach_trap.mach_trap_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MACHTRAP._serialized_start=71
  _MACHTRAP._serialized_end=224
  _MACHTRAP_TIMEBASE._serialized_start=192
  _MACHTRAP_TIMEBASE._serialized_end=216
# @@protoc_insertion_point(module_scope)
